Repository Jeonminje/Movie-information-system, pull requests merged in 2023-03, with the labels that each got.

#40 Member정보관련 유효성 검사 추가#39
  build.gradle
  src/main/java/study/movieservice/controller/MemberController.java
  src/main/java/study/movieservice/domain/ExceptionMessageConst.java
  src/main/java/study/movieservice/domain/member/MemberDTO.java
  src/main/java/study/movieservice/exception/GeneralExceptionHandler.java
  src/main/java/study/movieservice/service/MemberService.java
Labels: enhancement

#30 feature/영화 세부사항(리뷰 + 영화) 가져오기#28
  src/main/java/study/movieservice/controller/MovieController.java
  src/main/java/study/movieservice/domain/ExceptionMessageConst.java
  src/main/java/study/movieservice/domain/movie/MovieInfo.java
  src/main/java/study/movieservice/domain/movie/RatingVO.java
  src/main/java/study/movieservice/exception/GeneralExceptionHandler.java
  src/main/java/study/movieservice/repository/MovieMapper.java
  src/main/java/study/movieservice/repository/ReviewMapper.java
  src/main/java/study/movieservice/service/MovieService.java
  src/main/java/study/movieservice/service/ReviewService.java
  src/main/resources/study/movieservice/repository/MovieMapper.xml
  src/main/resources/study/movieservice/repository/ReviewMapper.xml
Labels: feature

#36 전체 영화목록, 상영중인 영화목록 불러오기#26
  src/main/java/study/movieservice/controller/MainController.java
  src/main/java/study/movieservice/domain/ExceptionMessageConst.java
  src/main/java/study/movieservice/domain/movie/MovieAndPosterVO.java
  src/main/java/study/movieservice/domain/movie/MovieListType.java
  src/main/java/study/movieservice/repository/MovieMapper.java
  src/main/java/study/movieservice/service/MovieService.java
  src/main/resources/study/movieservice/repository/MovieMapper.xml
Labels: feature

#38 MovieService 단위테스트 작성#34
  src/main/java/study/movieservice/domain/movie/Movie.java
  src/main/java/study/movieservice/domain/movie/Poster.java
  src/main/java/study/movieservice/repository/MovieMapper.java
  src/main/resources/study/movieservice/repository/MovieMapper.xml
  src/test/java/study/movieservice/service/MovieServiceTest.java
Labels: enhancement

#32 추천 기능 동시성문제해결#31
  build.gradle
  src/main/java/study/movieservice/controller/MovieController.java
  src/main/java/study/movieservice/controller/aop/RedissonLockAop.java
  src/main/java/study/movieservice/controller/aop/annotation/RedissonLock.java
  src/main/java/study/movieservice/domain/ExceptionMessageConst.java
  src/main/java/study/movieservice/domain/movie/Review.java
  src/main/java/study/movieservice/repository/ReviewMapper.java
  src/main/java/study/movieservice/service/RecommendService.java
  src/main/java/study/movieservice/service/ReviewService.java
  src/main/resources/study/movieservice/repository/ReviewMapper.xml
  src/test/java/study/movieservice/service/RecommendServiceTest.java
Labels: enhancement, feature

#44 리뷰 작성 수에 따른 회원등급 변경 #41
  src/main/java/study/movieservice/controller/MovieController.java
  src/main/java/study/movieservice/domain/ExceptionMessageConst.java
  src/main/java/study/movieservice/repository/MemberMapper.java
  src/main/java/study/movieservice/repository/ReviewMapper.java
  src/main/java/study/movieservice/service/ReviewService.java
  src/main/resources/study/movieservice/repository/MemberMapper.xml
  src/main/resources/study/movieservice/repository/ReviewMapper.xml
  src/test/java/study/movieservice/service/RecommendServiceTest.java
Labels: feature
